CREATE TABLE  "MAIL_MACHINE_MESSAGE" 
   (	"ID" NUMBER, 
	"SENDER" VARCHAR2(4000), 
	"RECEIVER" VARCHAR2(4000), 
	"SUBJECT" VARCHAR2(4000), 
	"MESSAGE" VARCHAR2(4000), 
	"TRASH" VARCHAR2(4000), 
	"MESSAGEDATE" DATE, 
	 CONSTRAINT "MAIL_MACHINE_MESSAGE_PK" PRIMARY KEY ("ID") ENABLE
   )